### PR TITLE
"Transpile" on the fly

### PR DESCRIPTION
**Pull request by EPOTH**
I now migrates two of my personal project from gwt to jwseet .
I do not use eclipse unfortunately , that is too heavy (for me ) on macosx . 
For my personal needs I created a small maven target allowing the transpiler to run on demand while listening to files change. Basically it do the same thing as the eclipse plugin .

Use it as follow

maven jsweet:watch 

Hope it helps .

Regards .

Jsweet is the best technology I have met since GWT in 2006. Congratulations to you and good luck.

### CODE REVIEW

**Comment by lgrignon** [comment]
Thanks for your message and contribution. It was a feature we were looking forward to add. 
I will take a look right away but there is a discrepancy between line endings which should cause the PR to be pretty hard to review.
I will keep you posted asap :)

**Comment by lgrignon** [comment]
I managed to compare properly the two branches. Don't you think we should share properties / methods between JSweetMojo & JSweetWatchMojo through an AbstractJSweetTranspilationMojo?
I think it would avoid duplication, hence bring more stability.
What do you think about it? If we agree on it, either you could do it in this PR or could I after the merge.

Please tell me.
Thanks again.

**Comment by lgrignon** [comment]
Actually I will merge and do it myself because I need this abstraction for the clean mojo

**Comment by lgrignon** [comment]
Why did you use javolution for this. Did you notice any performance problem due the use of standard collections? I try to keep the dependencies count as low as possible so I think I will remove it except if you noticed something special :)

Thanks again.

**Comment by EPOTH** [comment]
Hi louis . Sorry for the time lapse , i was very busy this afternoon .

First thank you to have accepted my pull request , i hope my code is not
too crapy for you .

I thought  that Javolution could be used for addressing memory problems
related to the endless loop used to compile on the fly.

Javolution is not really better than the standard collection , but in all
case consumes less memory ...

Your work on AbstractJSweetMojo is good , i will synchronize later .

Regards .







On 5 March 2016 at 03:18, Louis Grignon <notifications@github.com> wrote:

> Why did you use javolution for this. Did you notice any performance
> problem due the use of standard collections? I try to keep the dependencies
> count as low as possible so I think I will remove it except if you noticed
> something special :)
>
> Thanks again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lgrignon/jsweet-maven-plugin/pull/9#issuecomment-192623812>
> .
>



-- 
*Eric Ponthiaux *
*Développeur Senior , Consultant .*

*(+33) 06 14 67 13 11*

ponthiaux.eric@gmail.com

**Comment by lgrignon** [comment]
Thanks for your reply. No problem it's the week end ;)

I removed the reference to Javolution for now but please feel free to PR again if you notice any problem related to this. And to anything else actually :)

Hope you'll enjoy JSweet.
Regards.

**Comment by EPOTH** [comment]
Hello Louis ,

I wondered if this was really helpful to do another pull request for
changes I have implemented on your plugin.

I do not know if it's still closed to the jsweet philosophy.

Have a look when you have time.

https://github.com/EPOTH/jsweet-jersey-backend-example

And there is an example that will explain why I needed it.

https://github.com/EPOTH/jsweet-jersey-backend-example

Regards .


On 6 March 2016 at 18:04, Louis Grignon <notifications@github.com> wrote:

> Thanks for your reply. No problem it's the week end ;)
>
> I removed the reference to Javolution for now but please feel free to PR
> again if you notice any problem related to this. And to anything else
> actually :)
>
> Hope you'll enjoy JSweet.
> Regards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lgrignon/jsweet-maven-plugin/pull/9#issuecomment-192936339>
> .
>



-- 
*Eric Ponthiaux *
*Développeur Senior , Consultant .*

*(+33) 06 14 67 13 11*

ponthiaux.eric@gmail.com

**Comment by lgrignon** [comment]
Hello Eric, first of all, thank you very much to involve in the plugin development.

Your branch seems starting to get far from the original one, it's hard to compare the differences at a glance. I think the best idea is that you create a new PR so I could compare file by file :)

Let me know if you want to merge and I will give a look! 

Nice example mixing Jersey & JSweet with model sharing. as a matter of fact, I tried this use case on a project for a client and it worked perfectly. Very .. "sweet" :)

Thanks again.
Regards.

**Pull request merged**
